### ISSUE TITLE
Unify Pre & Post commit transactor decorators

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Database.Extensions#20]
As of right now we have two decorators to mimic 2.x commit hooks behavior:

- `PreCommitTransactor` - executes specified per type delegates right before transaction commit.
- `PostCommitTransactor` - executes specified per type delegates right after transaction commit.

This solution has a few issues:

- The `PostCommitTransactor` collects database changes while in the transaction and keeps them as a transactor state until the transaction is committed. This means that all database changes executed after the change collection will not trigger post commit hooks. This could happen if `PostCommitTransactor` is registered before `PreCommitTransactor`.
- Per type delegates have limited usage. With such approach it's not possible to enumerate all transaction changes. Polymorphism is also not supported, means it's required to manually register a delegate for all required types.

@bigwad [proposed](https://starcounter.slack.com/archives/GL199A0NL/p1592382865048100) to replace this solution with a single decorator which would combine both hooks into the following solution:

- Two events to subscribe: `BeforeCommit` & `AfterCommit`.
- The `BeforeCommit` method shall provide an enumerable with changes and a state object.
- The `BeforeCommit` subscribers can enumerate the changes and save required items in the state object.
- The state object is passed to the `AfterCommit` method.

With such implementation:

- Post/Pre commit hook ordering issue is solved.
- Transaction changes are enumerated only once.
- It's possible to enumerate all transaction changes together, not just per type.
- App developer has freedom to harvest all required changes for the post commit processing.

cc @per-samuelsson

**Comment by per-samuelsson** [comment]
> * The `BeforeCommit` method shall provide an enumerable with changes and a state object.

I think it should probably provide the database context. From that, changes are available.

**Comment by miyconst** [comment]
>I think it should probably provide the database context. From that, changes are available.

Agree, and that's how I done with my local implementation.

**Comment by per-samuelsson** [comment]
Done. Merged it https://github.com/Starcounter/Starcounter.Database.Extensions/commit/ca5744e4ae344dfec6e7619ffccdc8b90d3de849.
